# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KPWebsocket' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KPWebsocket
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SocketRocket', '~> 0.5.1'
  pod 'MJExtension', '~> 3.0.16'
  
end
